[server]
headless = true

[client]
showSidebarNavigation = true

[theme]
base = "light"
primaryColor = "#00A6D6"
backgroundColor = "#fbfcff"
secondaryBackgroundColor = "#ffffff"
textColor = "#111111"
font = "sans serif"
